### ISSUE TITLE
Can only connect to my own account

### ISSUE THREAD

**Issue by JayZhouzzj** [aeddi/DiscordRPC#7]
Thank you for writing this package! 

This is my first time developing things with discord. I'm trying to build a macOS toy app with a rich presence integration. I added some code and the whole thing works with my own account, but it cannot even authenticate when testing with other accounts. says "OAuth2 Error: invalid_scope: The requested scope is invalid, unknown, or malformed." I dug around and it seems discord has to whitelist my app, and they stopped doing that long time ago?

I saw you mentioned using IPC, is that supposed to bypass this? 

Thank you

**Comment by JayZhouzzj** [comment]
I figured it out. I don't need authentication to have rich presence 😅. Thank you again for writing this great package

**Comment by zenfty** [comment]
Hi,
Was wondering if you could show me how you managed to do this?
